# ===============================================================================
# ENRICHMENT DATA - Extended Hyper-V Event IDs
# ===============================================================================
# Supplements EventIds.ps1 with additional Hyper-V event coverage

$Script:State.EventIdLookup += @{
    # VMMS Events - VM Lifecycle (12000-12800)
    12000   = "Hyper-V VMMS: VM creation started"
    12002   = "Hyper-V VMMS: VM creation completed"
    12004   = "Hyper-V VMMS: VM deletion started"
    12006   = "Hyper-V VMMS: VM deletion completed"
    12010   = "Hyper-V VMMS: VM configuration modified"
    12012   = "Hyper-V VMMS: VM memory settings changed"
    12014   = "Hyper-V VMMS: VM processor settings changed"
    12020   = "Hyper-V VMMS: Virtual hard disk attached"
    12022   = "Hyper-V VMMS: Virtual hard disk detached"
    12040   = "Hyper-V VMMS: Virtual network adapter added"
    12042   = "Hyper-V VMMS: Virtual network adapter removed"
    12044   = "Hyper-V VMMS: Virtual network adapter connected"
    12046   = "Hyper-V VMMS: Virtual network adapter disconnected"
    12050   = "Hyper-V VMMS: VM import started"
    12052   = "Hyper-V VMMS: VM import completed"
    12054   = "Hyper-V VMMS: VM export started"
    12056   = "Hyper-V VMMS: VM export completed"
    12100   = "Hyper-V VMMS: VM heartbeat status healthy"
    12102   = "Hyper-V VMMS: VM heartbeat status critical"
    12200   = "Hyper-V VMMS: Dynamic Memory balancer adjustment"
    12202   = "Hyper-V VMMS: Dynamic Memory pressure notification"
    12300   = "Hyper-V VMMS: Resource metering data collected"
    12400   = "Hyper-V VMMS: Enhanced session mode connected"
    12402   = "Hyper-V VMMS: Enhanced session mode disconnected"
    12500   = "Hyper-V VMMS: VM saved state created"
    12502   = "Hyper-V VMMS: VM restored from saved state"
    12600   = "Hyper-V VMMS: Guest shutdown initiated"
    12602   = "Hyper-V VMMS: Guest shutdown completed"
    12700   = "Hyper-V VMMS: VM generation ID changed"
    12800   = "Hyper-V VMMS: Discrete device assignment configured"

    # Virtual Switch Events (10100-10200)
    10100   = "Hyper-V VSwitch: Virtual switch created"
    10102   = "Hyper-V VSwitch: Virtual switch deleted"
    10104   = "Hyper-V VSwitch: Virtual switch settings modified"
    10110   = "Hyper-V VSwitch: Port created"
    10112   = "Hyper-V VSwitch: Port deleted"
    10114   = "Hyper-V VSwitch: Port connected"
    10116   = "Hyper-V VSwitch: Port disconnected"
    10120   = "Hyper-V VSwitch: Extension enabled"
    10122   = "Hyper-V VSwitch: Extension disabled"
    10130   = "Hyper-V VSwitch: Port ACL rule applied"
    10132   = "Hyper-V VSwitch: Port ACL rule removed"
    10140   = "Hyper-V VSwitch: Port mirroring enabled"
    10142   = "Hyper-V VSwitch: Port mirroring disabled"
    10150   = "Hyper-V VSwitch: NIC teaming failover"
    10160   = "Hyper-V VSwitch: Bandwidth reservation applied"
    10200   = "Hyper-V VSwitch: Switch extension error"

    # Replication Events (32300-32600)
    32300   = "Hyper-V Replica: Replication enabled for VM"
    32302   = "Hyper-V Replica: Replication disabled for VM"
    32310   = "Hyper-V Replica: Initial replication started"
    32312   = "Hyper-V Replica: Initial replication completed"
    32314   = "Hyper-V Replica: Initial replication failed"
    32320   = "Hyper-V Replica: Delta replication cycle completed"
    32322   = "Hyper-V Replica: Delta replication cycle failed"
    32330   = "Hyper-V Replica: Replication health warning"
    32332   = "Hyper-V Replica: Replication health critical"
    32340   = "Hyper-V Replica: Planned failover started"
    32342   = "Hyper-V Replica: Planned failover completed"
    32350   = "Hyper-V Replica: Unplanned failover started"
    32352   = "Hyper-V Replica: Unplanned failover completed"
    32360   = "Hyper-V Replica: Test failover started"
    32362   = "Hyper-V Replica: Test failover completed"
    32370   = "Hyper-V Replica: Resynchronization required"
    32372   = "Hyper-V Replica: Resynchronization started"
    32374   = "Hyper-V Replica: Resynchronization completed"
    32400   = "Hyper-V Replica: Recovery point created"
    32500   = "Hyper-V Replica: Extended replication enabled"
    32600   = "Hyper-V Replica: Authorization entry updated"

    # Storage QoS Events (15000-15100)
    15000   = "Hyper-V Storage QoS: Policy created"
    15002   = "Hyper-V Storage QoS: Policy modified"
    15004   = "Hyper-V Storage QoS: Policy deleted"
    15010   = "Hyper-V Storage QoS: Policy applied to virtual disk"
    15012   = "Hyper-V Storage QoS: Policy removed from virtual disk"
    15020   = "Hyper-V Storage QoS: IOPS throttled - maximum exceeded"
    15022   = "Hyper-V Storage QoS: IOPS below minimum reservation"
    15030   = "Hyper-V Storage QoS: Storage performance warning"
    15040   = "Hyper-V Storage QoS: Flow created"
    15042   = "Hyper-V Storage QoS: Flow removed"
    15100   = "Hyper-V Storage QoS: Policy server unreachable"

    # Integration Services Events (23000-23100)
    23000   = "Hyper-V Integration: Integration services version mismatch"
    23002   = "Hyper-V Integration: Integration services update available"
    23010   = "Hyper-V Integration: Guest time synchronization activated"
    23012   = "Hyper-V Integration: Guest time synchronization deactivated"
    23020   = "Hyper-V Integration: Data exchange service started"
    23022   = "Hyper-V Integration: Data exchange service stopped"
    23030   = "Hyper-V Integration: Heartbeat service started"
    23032   = "Hyper-V Integration: Heartbeat service lost"
    23040   = "Hyper-V Integration: Guest shutdown service available"
    23042   = "Hyper-V Integration: Guest shutdown service unavailable"
    23050   = "Hyper-V Integration: VSS integration service started"
    23052   = "Hyper-V Integration: VSS integration service stopped"
    23060   = "Hyper-V Integration: Guest file copy service started"
    23062   = "Hyper-V Integration: Guest file copy service stopped"
    23100   = "Hyper-V Integration: Integration component error"

    # Checkpoint Events (13000-13100)
    13000   = "Hyper-V Checkpoint: Production checkpoint created"
    13002   = "Hyper-V Checkpoint: Production checkpoint failed, falling back to standard"
    13010   = "Hyper-V Checkpoint: Standard checkpoint created"
    13012   = "Hyper-V Checkpoint: Standard checkpoint creation failed"
    13020   = "Hyper-V Checkpoint: Checkpoint applied"
    13022   = "Hyper-V Checkpoint: Checkpoint apply failed"
    13030   = "Hyper-V Checkpoint: Checkpoint deleted"
    13032   = "Hyper-V Checkpoint: Checkpoint deletion failed"
    13040   = "Hyper-V Checkpoint: Checkpoint rename completed"
    13050   = "Hyper-V Checkpoint: Checkpoint export started"
    13052   = "Hyper-V Checkpoint: Checkpoint export completed"
    13060   = "Hyper-V Checkpoint: Checkpoint merge started"
    13062   = "Hyper-V Checkpoint: Checkpoint merge completed"
    13064   = "Hyper-V Checkpoint: Checkpoint merge failed"
    13100   = "Hyper-V Checkpoint: Maximum checkpoint limit reached"
}
