# ===============================================================================
# ENRICHMENT DATA - NPS/RADIUS Reason Codes
# ===============================================================================

$Script:State.NpsReasonLookup = @{
    0   = "IAS_SUCCESS"
    1   = "IAS_INTERNAL_ERROR"
    2   = "IAS_ACCESS_DENIED"
    3   = "IAS_MALFORMED_REQUEST"
    4   = "IAS_GLOBAL_CATALOG_UNAVAILABLE"
    5   = "IAS_DOMAIN_UNAVAILABLE"
    6   = "IAS_SERVER_UNAVAILABLE"
    7   = "IAS_NO_SUCH_DOMAIN"
    8   = "IAS_NO_SUCH_USER"
    16  = "Authentication failed: user credentials mismatch"
    17  = "Change password failure"
    18  = "Unable to use specified auth type"
    21  = "IAS_CHANGE_PASSWORD_FAILURE"
    22  = "Client could not be authenticated (certificate issue)"
    23  = "IAS_UNEXPECTED_ERROR"
    32  = "IAS_LOCAL_USERS_ONLY"
    33  = "IAS_PASSWORD_MUST_CHANGE"
    34  = "IAS_ACCOUNT_DISABLED"
    35  = "IAS_ACCOUNT_EXPIRED"
    36  = "IAS_ACCOUNT_LOCKED_OUT"
    37  = "IAS_INVALID_DAY_OF_WEEK"
    38  = "IAS_INVALID_TIME_OF_DAY"
    48  = "No matching connection request policy"
    49  = "No matching network policy"
    64  = "IAS_DIALIN_LOCKED_OUT"
    65  = "No dial-in permission for user"
    66  = "Restricted to specific called station"
    67  = "Restricted to specific calling station"
    68  = "Restricted to specific port type"
    69  = "Restricted to specific authentication type"
    70  = "Invalid EAP type configuration"
    73  = "Re-authentication required; session timed out"
    80  = "IAS_NO_RECORD"
    96  = "IAS_SESSION_TIMEOUT"
    97  = "IAS_UNEXPECTED_REQUEST"
    112 = "Remote RADIUS server did not respond"
    113 = "Remote RADIUS server unreachable"
    115 = "RADIUS accounting not supported"
    116 = "RADIUS proxy request timeout"
    117 = "Proxy retry limit reached"
    118 = "Invalid proxy response"
    256 = "IAS_NO_POLICY_MATCH"
    257 = "Server in probation period"
    258 = "Server not responding (health check)"
    259 = "SHV template not found"
    260 = "SHV conflict"
    261 = "NPS reached max shared secret length"
    262 = "NPS accounting encoding error"
}
