# ===============================================================================
# ENRICHMENT DATA - FortiSwitch Event Type/Subtype Descriptions
# ===============================================================================

$Script:FortiSwitchEventLookup = @{
    # Event Type/Subtype Combinations
    "event/switch"        = "Switch system event"
    "event/link"          = "Port link state change"
    "event/stp"           = "STP topology event"
    "event/poe"           = "PoE power event"
    "event/mac"           = "MAC table event"
    "event/lldp"          = "LLDP neighbor event"
    "event/dot1x"         = "802.1X authentication event"
    "event/loop-guard"    = "Loop guard detection"
    "event/trunk"         = "Trunk negotiation event"
    "event/system"        = "Switch system status event"
    "event/user"          = "Switch user authentication event"
    "event/ha"            = "Switch HA/stacking event"
    "event/mclag"         = "MC-LAG event"
    "event/igmp-snooping" = "IGMP snooping event"
    "event/dhcp-snooping" = "DHCP snooping event"
    "event/arp-guard"     = "ARP inspection/guard event"
    "event/storm-control" = "Storm control threshold event"
    "event/qos"           = "QoS policy event"
    "event/acl"           = "Switch ACL match event"
    "event/firmware"      = "Switch firmware event"
    "event/config"        = "Switch configuration change"
    "traffic/switch"      = "Switch forwarded traffic log"

    # FortiSwitch LogID Ranges to Functional Areas
    "S0001" = "System: General system events"
    "S0010" = "System: Boot/startup events"
    "S0020" = "System: Firmware/upgrade events"
    "S0030" = "System: Configuration events"
    "S0040" = "System: HA/stacking events"
    "S0100" = "Interface: Link up/down events"
    "S0110" = "Interface: Speed/duplex negotiation"
    "S0120" = "Interface: PoE power events"
    "S0130" = "Interface: Error/CRC events"
    "S0200" = "STP: Topology change events"
    "S0210" = "STP: Root bridge election"
    "S0220" = "STP: Port state transitions"
    "S0230" = "STP: BPDU guard violations"
    "S0300" = "MAC: MAC learning events"
    "S0310" = "MAC: MAC move/flap detection"
    "S0320" = "MAC: MAC table overflow"
    "S0400" = "LLDP: Neighbor discovery"
    "S0410" = "LLDP: Neighbor timeout/removal"
    "S0500" = "802.1X: Authentication success"
    "S0510" = "802.1X: Authentication failure"
    "S0520" = "802.1X: RADIUS timeout"
    "S0530" = "802.1X: MAC-based authentication"
    "S0600" = "Trunk: LACP negotiation"
    "S0610" = "Trunk: Member port added/removed"
    "S0700" = "Loop Guard: Loop detected"
    "S0710" = "Loop Guard: Port blocked"
    "S0720" = "Loop Guard: Port recovered"
    "S0800" = "Storm Control: Broadcast storm detected"
    "S0810" = "Storm Control: Multicast storm detected"
    "S0820" = "Storm Control: Unknown unicast storm detected"
    "S0900" = "QoS: Queue congestion event"
    "S0910" = "QoS: Policy applied/removed"
    "S1000" = "ACL: Access control list match"
    "S1010" = "ACL: Implicit deny hit"
    "S1100" = "IGMP: Group join/leave"
    "S1110" = "IGMP: Querier election"
    "S1200" = "DHCP Snooping: Untrusted DHCP server detected"
    "S1210" = "DHCP Snooping: Binding table entry"
}
